### ISSUE TITLE
Scroll Wheel Moving Hands

### ISSUE THREAD

**Issue by MatthewBernardon** [Cafezinhu/godot-vr-simulator#5]
Everything works great in my test project, however in the project I am currently working on, the scroll wheel is not behaving as normal.

Instead of moving the camera up and down, the scroll wheel is moving the hands up and down, spawning issues such as clipping through the floor when teleporting. 

I likely missed a step when setting up the XR functionality, if you know what could be causing this error please let me know.

**Comment by Cafezinhu** [comment]
This behavior happens when you have a PlayerBody and the camera y position goes bellow 0.5 or above PlayerBody.player_height_max - PlayerBody.player_head_height (2.1 by default). I added a way to limit the camera y movement between 0.5 and 2.0 in the default settings. You can also adjust those values in the XRSimulator 
![image](https://user-images.githubusercontent.com/38568712/232229361-01a36739-efa2-45df-a2b6-865d86c5b19e.png)
But I don't know if this is the best way to fix this issue.

You can download the update here:
https://github.com/Cafezinhu/godot-vr-simulator/releases/tag/v1.0.4

**Comment by MatthewBernardon** [comment]
Yup, increasing the camera's y-position to 0.5 fixed the issue. Thanks again!
